# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# القسم الرئيسي
[[main]]
  name = "Courses"
  pageRef = "series"
  weight = 10

[[main]]
  name = "Programming Projects"
  identifier = "projects"
  weight = 20

[[main]]
  name = "All Projects"
  parent = "projects"
  pageRef = "projects"
  weight = 21

[[main]]
  name = "Frontend Projects"
  parent = "projects"
  pageRef = "tags/frontend-projects"
  weight = 22

[[main]]
  name = "Backend Projects"
  parent = "projects"
  pageRef = "tags/backend-projects"
  weight = 23

[[main]]
  name = "Fullstack Projects"
  parent = "projects"
  pageRef = "tags/fullstack-projects"
  weight = 24

[[main]]
  name = "HTML & CSS Practical Apps"
  parent = "projects"
  pageRef = "tags/html-css-practical"
  weight = 25

[[main]]
  name = "JavaScript Practical Apps"
  parent = "projects"
  pageRef = "tags/js-practical"
  weight = 26

[[main]]
  name = "Vue Practical Apps"
  parent = "projects"
  pageRef = "tags/vue-practical"
  weight = 27

[[main]]
  name = "PHP Practical Apps"
  parent = "projects"
  pageRef = "tags/php-practical"
  weight = 28

[[main]]
  name = "Laravel Practical Apps"
  parent = "projects"
  pageRef = "tags/laravel-practical"
  weight = 29

[[main]]
  name = "Packages"
  identifier = "packages"
  weight = 30

[[main]]
  name = "JavaScript Libraries"
  parent = "packages"
  pageRef = "js-libraries"
  weight = 31

[[main]]
  name = "PHP Packages"
  parent = "packages"
  pageRef = "tags/php-packages"
  weight = 32

[[main]]
  name = "Laravel Packages"
  parent = "packages"
  pageRef = "tags/laravel-packages"
  weight = 33

[[main]]
  name = "Articles"
  identifier = "articles"
  weight = 40

[[main]]
  name = "All Educational Articles"
  parent = "articles"
  pageRef = "articles"
  weight = 41

[[main]]
  name = "Learn HTML"
  parent = "articles"
  pageRef = "tags/learn-html"
  weight = 42

[[main]]
  name = "Learn CSS"
  parent = "articles"
  pageRef = "tags/learn-css"
  weight = 43

[[main]]
  name = "Learn JavaScript"
  parent = "articles"
  pageRef = "tags/learn-js"
  weight = 44

[[main]]
  name = "Learn Vue"
  parent = "articles"
  pageRef = "tags/learn-vue"
  weight = 45

[[main]]
  name = "Learn PHP"
  parent = "articles"
  pageRef = "tags/learn-php"
  weight = 46

[[main]]
  name = "Learn MySQL"
  parent = "articles"
  pageRef = "tags/mysql"
  weight = 47

[[main]]
  name = "Learn Laravel"
  parent = "articles"
  pageRef = "tags/learn-laravel"
  weight = 48

[[main]]
  name = "Tools"
  identifier = "tools"
  pageRef = "tools"
  weight = 50

[[main]]
  name = "All Tools"
  parent = "tools"
  pageRef = "tools"
  weight = 51

[[main]]
  name = "Developer Tools"
  parent = "tools"
  pageRef = "tags/developer-tools"
  weight = 52

[[main]]
  name = "CSS Tools"
  parent = "tools"
  pageRef = "tags/css-tools"
  weight = 53

[[main]]
  name = "JavaScript Tools"
  parent = "tools"
  pageRef = "tags/js-tools"
  weight = 54

[[main]]
  name = "Technical SEO Tools"
  parent = "tools"
  pageRef = "tags/seo-tools"
  weight = 55

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[footer]]
  name = "Authors"
  pageRef = "authors"
  weight = 30

[[footer]]
  name = "About CodeZelo"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "Privacy Policy"
  pageRef = "Privacy Policy"
  weight = 50

[[footer]]
  name = "Terms of Use"
  pageRef = "terms-of-use"
  weight = 60

[[footer]]
  name = "Contact Us"
  pageRef = "contact-us"
  weight = 70

[[footer]]
  name = "Newsletter"
  pageRef = "newsletter"
  weight = 80
