# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# القسم الرئيسي
[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "Tutorials"
  pageRef = "series"
  weight = 20

[[main]]
  name = "Articles"
  pageRef = "articles"
  weight = 30

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[footer]]
  name = "Authors"
  pageRef = "authors"
  weight = 30

[[footer]]
  name = "About CodeZelo"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "Privacy Policy"
  pageRef = "Privacy Policy"
  weight = 50

[[footer]]
  name = "Terms of Use"
  pageRef = "terms-of-use"
  weight = 60

[[footer]]
  name = "Contact Us"
  pageRef = "contact-us"
  weight = 70

[[footer]]
  name = "Newsletter"
  pageRef = "newsletter"
  weight = 80
